### ISSUE TITLE
Connector J25 pinout

### ISSUE THREAD

**Issue by VojislavM** [IRNAS/IoT-battery-pack#24]
Current pinout of connector J25 is not OK. 
![image](https://user-images.githubusercontent.com/8199477/27173861-535c6960-51ba-11e7-954a-5ceb0bd776c3.png)

SW1 and SW2 pins are inverted

This is because of the error in the schematics EN2 is connected to the J5 instead of J11, and EN1 is connected to the J11 instead of J5.

![image](https://user-images.githubusercontent.com/8199477/27174010-d2e3543c-51ba-11e7-88d9-51b15ee669f8.png)

**Comment by VojislavM** [comment]
This is how it should be:
![image](https://user-images.githubusercontent.com/8199477/27174125-4a4d417c-51bb-11e7-9296-6348e31df72d.png)

**Comment by mucek** [comment]
Replaced connection between J25 and schottky diodes. Net names (EN1, EN2) in schematics are still wrong and should be replaced (EN1 > EN2, EN2 > EN1)
